import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  //base: "/silenceroad",
  title: "My Awesome Project",
  description: "A VitePress Site",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: '首页', link: '/' },
      { text: '预科班', link: '/matriculation' },
      { text: '本科班', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 00' },
      { text: '研究班', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 01' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar:
      {
        '/undergraduate/':[
	  {
	    text: '楞严经',
	    collapsed: true,
	    items: [
              { text: '00', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 00' },
              { text: '01', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 01' },
              { text: '02', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 02' },
              { text: '03', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 03' },
              { text: '04', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 04' },
              { text: '05', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 05' },
              { text: '06', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 06' },
              { text: '07', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 07' },
              { text: '08', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 08' },
              { text: '09', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 09' },
              { text: '10', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 10' },
              { text: '11', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 11' },
              { text: '12', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 12' },
              { text: '13', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 13' },
              { text: '14', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 14' },
              { text: '15', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 15' },
              { text: '16', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 16' },
              { text: '17', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 17' },
              { text: '18', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 18' },
              { text: '19', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 19' },
              { text: '20', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 20' },
              { text: '21', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 21' },
              { text: '22', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 22' },
              { text: '23', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 23' },
              { text: '24', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 24' },
              { text: '25', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 25' },
              { text: '26', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 26' },
              { text: '27', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 27' },
              { text: '28', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 28' },
              { text: '29', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 29' },
              { text: '30', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 30' },
              { text: '31', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 31' },
              { text: '32', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 32' },
              { text: '33', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 33' },
              { text: '34', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 34' },
              { text: '35', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 35' },
              { text: '36', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 36' },
              { text: '37', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 37' },
              { text: '38', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 38' },
              { text: '39', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 39' },
              { text: '40', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 40' },
              { text: '41', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 41' },
              { text: '42', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 42' },
              { text: '43', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 43' },
              { text: '44', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 44' },
              { text: '45', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 45' },
              { text: '46', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 46' },
              { text: '47', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 47' },
              { text: '48', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 48' },
              { text: '49', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 49' },
              { text: '50', link: '/undergraduate/15SurangamaSutra/15 SurangamaSutra 50' },
              { text: 'Runtime API Examples', link: '/api-examples' }
            ]
          },
	  {
	    text: '金刚经',
	    collapsed: true,
	    items: [
              { text: '00', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 00' },
              { text: '01', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 01' },
              { text: '02', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 02' },
              { text: '03', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 03' },
              { text: '04', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 04' },
              { text: '05', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 05' },
              { text: '06', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 06' },
              { text: '07', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 07' },
              { text: '08', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 08' },
              { text: '09', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 09' },
              { text: '10', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 10' },
              { text: '11', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 11' },
              { text: '12', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 12' },
              { text: '13', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 13' },
              { text: '14', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 13' },
              { text: '15', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 15' },
              { text: '16', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 16' },
              { text: '17', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 17' },
              { text: '18', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 18' },
              { text: '19', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 19' },
              { text: '20', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 20' },
              { text: '21', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 21' },
              { text: '22', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 22' },
              { text: '23', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 23' },
              { text: '24', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 24' },
              { text: '25', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 25' },
              { text: '26', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 26' },
              { text: '27', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 27' },
              { text: '28', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 28' },
              { text: '29', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 29' },
              { text: '30', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 30' },
              { text: '31', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 31' },
              { text: '32', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 32' },
              { text: '33', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 33' },
              { text: '34', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 34' },
              { text: '35', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 35' },
              { text: '36', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 36' },
              { text: '37', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 37' },
              { text: '38', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 38' },
              { text: '39', link: '/undergraduate/13DiamondSutra/13 DiamondSutra 39' },
            ]
   	  },
          {
	    text: '物不迁论',
	    collapsed: true,
	    items: [
              { text: '00', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 00' },
              { text: '01', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 01' },
              { text: '02', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 02' },
              { text: '03', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 03' },
              { text: '04', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 04' },
              { text: '05', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 05' },
              { text: '06', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 06' },
              { text: '07', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 07' },
              { text: '08', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 08' },
              { text: '09', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 09' },
              { text: '10', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 10' },
              { text: '11', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 11' },
              { text: '12', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 12' },
              { text: '13', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 13' },
              { text: '14', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 13' },
              { text: '15', link: '/undergraduate/17OntheStaticStateofThings/17 OntheStaticStateofThings 15' },
            ]
          },
 	  {
	    text: '大乘百法明门论',
	    collapsed: true,
	    items: [
              { text: '01', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 01' },
              { text: '02', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 02' },
              { text: '03', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 03' },
              { text: '04', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 04' },
              { text: '05', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 05' },
              { text: '06', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 06' },
              { text: '07', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 07' },
              { text: '08', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 08' },
              { text: '09', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 09' },
              { text: '10', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 10' },
              { text: '11', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 11' },
              { text: '12', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 12' },
              { text: '13', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 13' },
              { text: '14', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 13' },
              { text: '15', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 15' },
              { text: '16', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 16' },
              { text: '17', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 17' },
              { text: '18', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 18' },
              { text: '19', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 19' },
              { text: '20', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 20' },
              { text: '21', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 21' },
              { text: '22', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 22' },
              { text: '23', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 23' },
              { text: '24', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 24' },
              { text: '25', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 25' },
              { text: '26', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 26' },
              { text: '27', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 27' },
              { text: '28', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 28' },
              { text: '29', link: '/undergraduate/18OneHundredDharmas/18 OneHundredDharmas 29' },
            ]
   	  },
  	  {
	    text: '八识规矩颂',
	    collapsed: true,
	    items: [
              { text: '00', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 00' },
              { text: '01', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 01' },
              { text: '02', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 02' },
              { text: '03', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 03' },
              { text: '04', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 04' },
              { text: '05', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 05' },
              { text: '06', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 06' },
              { text: '07', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 07' },
              { text: '08', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 08' },
              { text: '09', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 09' },
              { text: '10', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 10' },
              { text: '11', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 11' },
              { text: '12', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 12' },
              { text: '13', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 13' },
              { text: '14', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 13' },
              { text: '15', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 15' },
              { text: '16', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 16' },
              { text: '17', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 17' },
              { text: '18', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 18' },
              { text: '19', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 19' },
              { text: '20', link: '/undergraduate/19VersesDelineatingtheEightConsciousnesses/19 VersesDelineatingtheEightConsciousnesses 20' },
            ]
   	  },
       ],
       '/postgraduate/':[
	  {
	    text: '净土源流',
	    collapsed: true,
	    items: [
              { text: '00', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 00' },
              { text: '01', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 01' },
              { text: '02', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 02' },
              { text: '03', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 03' },
              { text: '04', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 04' },
              { text: '05', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 05' },
              { text: '06', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 06' },
              { text: '07', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 07' },
              { text: '08', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 08' },
              { text: '09', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 09' },
              { text: '10', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 10' },
              { text: '11', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 11' },
              { text: '12', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 12' },
              { text: '13', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 13' },
              { text: '14', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 14' },
              { text: '15', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 15' },
              { text: '16', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 16' },
              { text: '17', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 17' },
              { text: '18', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 18' },
              { text: '19', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 19' },
              { text: '20', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 20' },
              { text: '21', link: '/postgraduate/21TheHistoryofPureLandBuddhism/21 The History of Pure Land Buddhism 21' },
	    ]
	},
	{
	    text: '佛说无量寿经',
	    collapsed: true,
	    items: [
              { text: '01', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 01' },
              { text: '02', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 02' },
              { text: '03', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 03' },
              { text: '04', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 04' },
              { text: '05', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 05' },
              { text: '06', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 06' },
              { text: '07', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 07' },
              { text: '08', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 08' },
              { text: '09', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 09' },
              { text: '10', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 10' },
              { text: '11', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 11' },
              { text: '12', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 12' },
              { text: '13', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 13' },
              { text: '14', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 14' },
              { text: '15', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 15' },
              { text: '16', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 16' },
              { text: '17', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 17' },
              { text: '18', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 18' },
              { text: '19', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 19' },
              { text: '20', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 20' },
              { text: '21', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 21' },
              { text: '22', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 22' },
              { text: '23', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 23' },
              { text: '24', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 24' },
              { text: '25', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 25' },
              { text: '26', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 26' },
              { text: '27', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 27' },
              { text: '28', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 28' },
              { text: '29', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 29' },
              { text: '30', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 30' },
              { text: '31', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 31' },
              { text: '32', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 32' },
              { text: '33', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 33' },
              { text: '34', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 34' },
              { text: '35', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 35' },
              { text: '36', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 36' },
              { text: '37', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 37' },
              { text: '38', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 38' },
              { text: '39', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 39' },
              { text: '40', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 40' },
              { text: '41', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 41' },
              { text: '42', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 42' },
              { text: '43', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 43' },
              { text: '44', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 44' },
              { text: '45', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 45' },
              { text: '46', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 46' },
              { text: '47', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 47' },
              { text: '48', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 48' },
              { text: '49', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 49' },
              { text: '50', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 50' },
              { text: '51', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 51' },
              { text: '52', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 52' },
              { text: '53', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 53' },
              { text: '54', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 54' },
              { text: '55', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 55' },
              { text: '56', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 56' },
              { text: '57', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 57' },
              { text: '58', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 58' },
              { text: '59', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 59' },
              { text: '60', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 60' },
              { text: '61', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 61' },
              { text: '62', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 62' },
              { text: '63', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 63' },
              { text: '64', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 64' },
              { text: '65', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 65' },
              { text: '66', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 66' },
              { text: '67', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 67' },
              { text: '68', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 68' },
              { text: '69', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 69' },
              { text: '70', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 70' },
              { text: '71', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 71' },
              { text: '72', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 72' },
              { text: '73', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 73' },
              { text: '74', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 74' },
              { text: '75', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 75' },
              { text: '76', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 76' },
              { text: '77', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 77' },
              { text: '78', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 78' },
              { text: '79', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 79' },
              { text: '80', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 80' },
              { text: '81', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 81' },
              { text: '82', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 82' },
              { text: '83', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 83' },
              { text: '84', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 84' },
              { text: '85', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 85' },
              { text: '86', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 86' },
              { text: '87', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 87' },
              { text: '88', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 88' },
              { text: '89', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 89' },
              { text: '90', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 90' },
              { text: '91', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 91' },
              { text: '92', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 92' },
              { text: '93', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 93' },
              { text: '94', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 94' },
              { text: '95', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 95' },
              { text: '96', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 96' },
              { text: '97', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 97' },
              { text: '98', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 98' },
              { text: '99', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 99' },
              { text: '100', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 100' },
              { text: '101', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 101' },
              { text: '102', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 102' },
              { text: '103', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 103' },
              { text: '104', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 104' },
              { text: '105', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 105' },
              { text: '106', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 106' },
              { text: '107', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 107' },
              { text: '108', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 108' },
              { text: '109', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 109' },
              { text: '110', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 110' },
              { text: '111', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 111' },
              { text: '112', link: '/postgraduate/22TheAmitāyusSutra/22 The Amitāyus Sutra 112' },
	    ]
           },
	],
      },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ],
//#    footer: {
//#      message: 'Released under the MIT License.',
//#      copyright: 'Copyright © 2019-present Evan You'
//#    }
  }
})
